=== cmwshang/docdynamo/doc/xml/dtd/manifest.dtd
<!ELEMENT doc (variable-list, source-list, render-list)>

<!ELEMENT variable-list (variable+)>
<!ELEMENT variable (#PCDATA)>
    <!ATTLIST variable key CDATA #REQUIRED>
    <!ATTLIST variable eval CDATA "n">
    <!ATTLIST variable keyword CDATA "default">

<!ELEMENT title1 (#PCDATA)>
<!ELEMENT title2 (#PCDATA)>
<!ELEMENT title3 (#PCDATA)>

<!ELEMENT source-list (source+)>
<!ELEMENT source EMPTY>
    <!ATTLIST source key CDATA #REQUIRED>
    <!ATTLIST source type CDATA "">

<!ELEMENT render-list (render+)>
<!ELEMENT render (title1?, title2?, title3?, render-source+)>
    <!ATTLIST render type CDATA #REQUIRED>
    <!ATTLIST render compact CDATA "n">
    <!ATTLIST render pretty CDATA "n">
    <!ATTLIST render file CDATA "">
<!ELEMENT render-source EMPTY>
    <!ATTLIST render-source key CDATA #REQUIRED>
    <!ATTLIST render-source source CDATA "">
    <!ATTLIST render-source file CDATA "">
    <!ATTLIST render-source menu CDATA "">

=== cmwshang/docdynamo/doc/manifest.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE doc SYSTEM "manifest.dtd">
<doc>
    <!-- System-wide variables  -->
    <variable-list>
        <variable key="dash">-</variable>
        <variable key="project-url-root">/</variable>
        <variable key="organization">Crunchy Data Solutions, Inc.</variable>
        <variable key="project">Crunchy Containers</variable>

        <!-- Logo locations -->
        <variable key="project-logo">logo.svg</variable>
        <variable key="logo">{[doc-path]}/output/latex/logo</variable>

        <!-- HTML variables  -->
        <variable key="prepare-date" eval="y">
            use Time::Local;

            my ($second, $minute , $hour, $mday, $month, $year) = localtime();
            $year += 1900;

            my @stryMonth = ('January', 'February', 'March', 'April', 'May', 'June',
                             'July', 'August', 'September', 'October', 'November', 'December');

            $stryMonth[$month] . ' ' . $mday . ', ' . $year;
        </variable>
        <variable key="html-logo">&lt;img src=&quot;{[project-logo]}&quot;&gt;</variable>

        <!-- PDF variables -->
        <variable key="pdf-title1">{[project]}</variable>
        <variable key="pdf-title2">Installation Guide</variable>
        <variable key="pdf-title3">DRAFT</variable>

    </variable-list>

    <source-list>
        <source key="install"/>
        <source key="usage"/>
        <source key="examples"/>
        <source key="containers"/>
    </source-list>

    <render-list>
        <render type="html">
            <footer-center>Prepared by Crunchy Data Solutions, Inc. &amp;mdash; {[prepare-date]}</footer-center>
            <render-source key="install" menu="Home"/>
            <render-source key="usage" menu="Usage"/>
            <render-source key="examples" menu="Examples"/>
            <render-source key="containers" menu="Containers"/>
        </render>

        <render type="pdf" file="Crunchy">
            <title1>{[pdf-title1]}</title1>
            <title2>{[pdf-title2]}</title2>
            <title3>{[pdf-title3]}</title3>
            <footer-left>{[pdf-title1]} {[pdf-title2]}\\{[pdf-title3]}</footer-left>
            <footer-center>\ \\-\ \thepage\ -</footer-center>
            <footer-right>{[organization]}\\\today</footer-right>
            <render-source key="install"/>
            <render-source key="containers"/>
        </render>

        <render type="markdown">
            <render-source key="containers" file="CONTAINERS.md"/>
        </render>
    </render-list>
</doc>

=== cmwshang/docdynamo/manifest.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE doc SYSTEM "manifest.dtd">
<doc>
    <!-- System-wide variables  -->
    <variable-list>
        <variable key="dash">-</variable>
        <variable key="project-url-root">/</variable>
        <variable key="organization">Open Source</variable>
        <variable key="project">DocDynamo</variable>
        <variable key="project-exe">/docdynamo/bin/docdynamo</variable>

        <!-- Logo locations -->
        <variable key="project-logo">docdynamo.png</variable>
        <variable key="logo">{[doc-path]}/output/latex/logo</variable>

        <!-- HTML variables  -->
        <variable key="prepare-date" eval="y">
            use Time::Local;

            my ($second, $minute , $hour, $mday, $month, $year) = localtime();
            $year += 1900;

            my @stryMonth = ('January', 'February', 'March', 'April', 'May', 'June',
                             'July', 'August', 'September', 'October', 'November', 'December');

            $stryMonth[$month] . ' ' . $mday . ', ' . $year;
        </variable>
        <variable key="html-logo">&lt;img src=&quot;{[project-logo]}&quot;&gt;</variable>

        <!-- PDF variables -->
        <variable key="pdf-install-subtitle">User Guide</variable>
        <variable key="pdf-install-version">DRAFT</variable>

    </variable-list>

    <source-list>
        <source key="about"/>
        <source key="user-guide"/>
    </source-list>

    <render-list>
        <render type="html">
            <!-- <footer-center>Prepared {[prepare-date]}</footer-center> -->
            <render-source key="about" menu="About"/>
            <render-source key="user-guide" menu="User Guide"/>
        </render>

        <render type="pdf" file="User-Guide">
            <title1>{[project]}</title1>
            <title2>{[pdf-install-subtitle]}</title2>
            <title3>{[pdf-install-version]}</title3>
            <footer-left>{[project]} {[pdf-install-subtitle]}\\{[pdf-install-version]}</footer-left>
            <footer-center>\ \\-\ \thepage\ -</footer-center>
            <footer-right>{[organization]}\\\today</footer-right>
            <render-source key="about"/>
            <render-source key="user-guide"/>
        </render>

        <render type="markdown">
            <render-source key="user-guide" file="README.md"/>
        </render>
    </render-list>
</doc>
